### ISSUE TITLE
Just to talk 

### ISSUE THREAD

**Issue by 404-ghost** [swagkarna/Amazon-payment-gateway-phishing#1]
Hi bro I need to talk to you
Need one help

**Comment by swagkarna** [comment]
You can chat  here

**Comment by 404-ghost** [comment]
OK bro

**Comment by 404-ghost** [comment]
U r from Chennai?

**Comment by 404-ghost** [comment]
U r from Chennai?

**Comment by swagkarna** [comment]
Yeah y

**Comment by 404-ghost** [comment]
I planing to build a thing can v do it
Will u help me?

**Comment by swagkarna** [comment]
About what Explain in detail

**Comment by 404-ghost** [comment]
I can't explain here

**Comment by swagkarna** [comment]
Just talk here i will delete  conversation later

**Comment by 404-ghost** [comment]
I want to build a cryptojacking malware
Do u have any idea?

**Comment by 404-ghost** [comment]
I want to build a cryptojacking malware
U have any Idea m

**Comment by 404-ghost** [comment]
Hello?

**Comment by 404-ghost** [comment]
Hello bro what happen

**Comment by swagkarna** [comment]
Whether i need to code or you can code the malware

**Comment by 404-ghost** [comment]
V both
But I need to learn about it more
If u join and  help me out It will be easy

**Comment by swagkarna** [comment]
First Learn bro and then ask doubt
